api:
  host: "0.0.0.0"
  port: "8083"
  basePath: "/api/v1"

api-process:
  host: "process-api-toystory-am5nwd.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  basePath: "/api/v1"
  path:
    customers: "/customers"
    orders: "/orders"

queue:
  user: "artemis"
  pass: "artemispassword"
  brokerurl: "localhost:61616"
  reconnectionstrategy: "5000"
  attempts: "4"


#queue:
#  user: "artemis"
#  pass: "yiil67n3dj0170cz5trchzfsdcdgi7a9"
#  brokerurl: "kodama.proxy.rlwy.net:18114"
#  reconnectionstrategy: "5000"
#  attempts: "4"

#api-process:
#  host: "0.0.0.0"
#  port: "8082"
#  basePath: "/api/v1"
#  path:
#    customers: "/customers"
#    orders: "/orders"