<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:mule="http://www.mulesoft.org/schema/mule/core" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mulesoft.org/schema/mule/anypoint-mq" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"></xs:import>
  <xs:import namespace="http://www.mulesoft.org/schema/mule/core" schemaLocation="http://www.mulesoft.org/schema/mule/core/current/mule.xsd"></xs:import>
  <xs:import namespace="http://www.mulesoft.org/schema/mule/tls" schemaLocation="http://www.mulesoft.org/schema/mule/tls/current/mule-tls.xsd"></xs:import>
  <xs:import namespace="http://www.mulesoft.org/schema/mule/tls" schemaLocation="http://www.mulesoft.org/schema/mule/tls/current/mule-tls.xsd"></xs:import>
  <xs:complexType name="com.mulesoft.extension.mq.api.source.SubscriberFactory">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractExtensionType"></xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns:mule="http://www.mulesoft.org/schema/mule/core" xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" type="anypoint-mq:com.mulesoft.extension.mq.api.source.SubscriberFactory" substitutionGroup="mule:abstract-shared-extension" abstract="true" name="global-abstract-subscriber-factory"></xs:element>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" type="anypoint-mq:com.mulesoft.extension.mq.api.source.SubscriberFactory" abstract="true" name="abstract-subscriber-factory"></xs:element>
  <xs:complexType name="com.mulesoft.extension.mq.api.source.PollingTypeSubscriberFactory">
    <xs:complexContent>
      <xs:extension xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" base="anypoint-mq:com.mulesoft.extension.mq.api.source.SubscriberFactory">
        <xs:sequence minOccurs="1" maxOccurs="1">
          <xs:element xmlns:mule="http://www.mulesoft.org/schema/mule/core" minOccurs="1" maxOccurs="1" ref="mule:scheduling-strategy"></xs:element>
        </xs:sequence>
        <xs:attribute xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="mule:substitutableInt" use="optional" default="10" name="fetchSize"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" type="anypoint-mq:com.mulesoft.extension.mq.api.source.PollingTypeSubscriberFactory" substitutionGroup="anypoint-mq:abstract-subscriber-factory" abstract="true" name="abstract-polling"></xs:element>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" substitutionGroup="anypoint-mq:abstract-polling" name="polling">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="anypoint-mq:com.mulesoft.extension.mq.api.source.PollingTypeSubscriberFactory"></xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="com.mulesoft.extension.mq.api.source.PrefetchTypeSubscriberFactory">
    <xs:complexContent>
      <xs:extension xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" base="anypoint-mq:com.mulesoft.extension.mq.api.source.SubscriberFactory">
        <xs:attribute xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="mule:substitutableInt" use="optional" default="30" name="maxLocalMessages"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" type="anypoint-mq:com.mulesoft.extension.mq.api.source.PrefetchTypeSubscriberFactory" substitutionGroup="anypoint-mq:abstract-subscriber-factory" abstract="true" name="abstract-prefetch"></xs:element>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" substitutionGroup="anypoint-mq:abstract-prefetch" name="prefetch">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="anypoint-mq:com.mulesoft.extension.mq.api.source.PrefetchTypeSubscriberFactory"></xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="com.mulesoft.extension.mq.api.circuit.CircuitBreakerConfiguration">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractExtensionType">
        <xs:attribute type="xs:string" use="optional" name="onErrorTypes"></xs:attribute>
        <xs:attribute type="mule:substitutableInt" use="required" name="errorsThreshold"></xs:attribute>
        <xs:attribute type="mule:substitutableLong" use="required" name="tripTimeout"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="java.util.concurrent.TimeUnitEnumType" use="optional" default="MILLISECONDS" name="tripTimeoutUnit"></xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns:mule="http://www.mulesoft.org/schema/mule/core" substitutionGroup="mule:abstract-shared-extension" abstract="true" name="abstract-circuit-breaker"></xs:element>
  <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" substitutionGroup="anypoint-mq:abstract-circuit-breaker" name="circuit-breaker">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="anypoint-mq:com.mulesoft.extension.mq.api.circuit.CircuitBreakerConfiguration">
          <xs:attribute type="xs:string" use="optional" name="name"></xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element xmlns:mule="http://www.mulesoft.org/schema/mule/core" substitutionGroup="mule:abstract-shared-extension" name="config">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="mule:abstractExtensionType">
          <xs:annotation>
            <xs:documentation>Default configuration</xs:documentation>
          </xs:annotation>
          <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element minOccurs="1" maxOccurs="1" ref="mule:abstractConnectionProvider"></xs:element>
            <xs:element minOccurs="0" maxOccurs="1" ref="mule:expiration-policy"></xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" use="required" name="name">
            <xs:annotation>
              <xs:documentation>The identifier of this element used to reference it in other components</xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element xmlns:mule="http://www.mulesoft.org/schema/mule/core" substitutionGroup="mule:abstractConnectionProvider" name="connection">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="mule:abstractConnectionProviderType">
          <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element minOccurs="0" maxOccurs="1" ref="mule:reconnection"></xs:element>
            <xs:element xmlns:tls="http://www.mulesoft.org/schema/mule/tls" minOccurs="0" maxOccurs="1" ref="tls:context"></xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="proxy">
              <xs:complexType>
                <xs:complexContent>
                  <xs:extension base="mule:abstractExtensionType">
                    <xs:sequence></xs:sequence>
                    <xs:attribute type="mule:expressionString" use="optional" name="host"></xs:attribute>
                    <xs:attribute type="mule:expressionInt" use="optional" name="port"></xs:attribute>
                    <xs:attribute type="mule:expressionString" use="optional" name="username"></xs:attribute>
                    <xs:attribute type="mule:expressionString" use="optional" name="password"></xs:attribute>
                  </xs:extension>
                </xs:complexContent>
              </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="tcp-client-socket-properties">
              <xs:complexType>
                <xs:complexContent>
                  <xs:extension base="mule:abstractExtensionType">
                    <xs:sequence></xs:sequence>
                    <xs:attribute type="mule:expressionInt" use="optional" name="sendBufferSize"></xs:attribute>
                    <xs:attribute type="mule:expressionInt" use="optional" name="receiveBufferSize"></xs:attribute>
                    <xs:attribute type="mule:expressionInt" use="optional" name="clientTimeout"></xs:attribute>
                    <xs:attribute type="mule:expressionBoolean" use="optional" default="true" name="sendTcpNoDelay"></xs:attribute>
                    <xs:attribute type="mule:expressionInt" use="optional" name="linger"></xs:attribute>
                    <xs:attribute type="mule:expressionBoolean" use="optional" default="false" name="keepAlive"></xs:attribute>
                    <xs:attribute type="mule:expressionInt" use="optional" default="30000" name="connectionTimeout"></xs:attribute>
                  </xs:extension>
                </xs:complexContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute type="xs:string" use="optional" name="tlsContext"></xs:attribute>
          <xs:attribute type="mule:expressionString" use="optional" default="https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/&lt;organization_id&gt;/environments/&lt;environment_id&gt;" name="url"></xs:attribute>
          <xs:attribute type="mule:expressionString" use="required" name="clientId"></xs:attribute>
          <xs:attribute type="mule:expressionString" use="required" name="clientSecret"></xs:attribute>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  <xs:element xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="SubscriberType" substitutionGroup="mule:abstract-message-source" name="subscriber"></xs:element>
  <xs:complexType name="SubscriberType">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractMessageSourceType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-redelivery-policy"></xs:element>
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-byte-streaming-strategy"></xs:element>
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-reconnection-strategy"></xs:element>
          <xs:element minOccurs="0" maxOccurs="1" name="subscriber-type">
            <xs:complexType>
              <xs:choice minOccurs="1" maxOccurs="1">
                <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" minOccurs="1" maxOccurs="1" ref="anypoint-mq:abstract-subscriber-factory"></xs:element>
                <xs:element xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" minOccurs="1" maxOccurs="1" ref="anypoint-mq:global-abstract-subscriber-factory"></xs:element>
              </xs:choice>
            </xs:complexType>
          </xs:element>
          <xs:element minOccurs="0" maxOccurs="1" name="circuit-breaker">
            <xs:complexType>
              <xs:complexContent>
                <xs:extension xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq" base="anypoint-mq:com.mulesoft.extension.mq.api.circuit.CircuitBreakerConfiguration"></xs:extension>
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" use="required" name="destination"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="com.mulesoft.extension.mq.api.modes.SubscriberAckModeEnumType" use="optional" default="AUTO" name="acknowledgementMode"></xs:attribute>
        <xs:attribute type="mule:substitutableLong" use="optional" default="0" name="acknowledgementTimeout"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="java.util.concurrent.TimeUnitEnumType" use="optional" default="MILLISECONDS" name="acknowledgementTimeoutUnit"></xs:attribute>
        <xs:attribute type="xs:string" use="optional" name="circuitBreaker"></xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputMimeType">
          <xs:annotation>
            <xs:documentation>The mime type of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputEncoding">
          <xs:annotation>
            <xs:documentation>The encoding of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:substitutableBoolean" use="optional" name="primaryNodeOnly">
          <xs:annotation>
            <xs:documentation>Whether this source should only be executed on the primary node when runnning in Cluster</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" use="required" name="config-ref">
          <xs:annotation>
            <xs:documentation>The name of the configuration to be used to execute this component</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="AckType" substitutionGroup="mule:abstract-operator" name="ack"></xs:element>
  <xs:complexType name="AckType">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractOperatorType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-reconnection-strategy"></xs:element>
        </xs:sequence>
        <xs:attribute type="mule:expressionString" use="required" name="ackToken"></xs:attribute>
        <xs:attribute type="xs:string" use="required" name="config-ref">
          <xs:annotation>
            <xs:documentation>The name of the configuration to be used to execute this component</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="ConsumeType" substitutionGroup="mule:abstract-operator" name="consume"></xs:element>
  <xs:complexType name="ConsumeType">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractOperatorType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-byte-streaming-strategy"></xs:element>
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-reconnection-strategy"></xs:element>
        </xs:sequence>
        <xs:attribute type="mule:expressionString" use="required" name="destination"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="com.mulesoft.extension.mq.api.modes.ConsumerAckModeEnumType" use="optional" default="IMMEDIATE" name="acknowledgementMode"></xs:attribute>
        <xs:attribute type="mule:expressionLong" use="optional" default="0" name="acknowledgementTimeout"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="java.util.concurrent.TimeUnitEnumType" use="optional" default="MILLISECONDS" name="acknowledgementTimeoutUnit"></xs:attribute>
        <xs:attribute type="mule:expressionLong" use="optional" default="10000" name="pollingTime"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="java.util.concurrent.TimeUnitEnumType" use="optional" default="MILLISECONDS" name="pollingTimeUnit"></xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputMimeType">
          <xs:annotation>
            <xs:documentation>The mime type of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputEncoding">
          <xs:annotation>
            <xs:documentation>The encoding of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" use="required" name="config-ref">
          <xs:annotation>
            <xs:documentation>The name of the configuration to be used to execute this component</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" use="optional" name="target">
          <xs:annotation>
            <xs:documentation>The name of a variable on which the operation's output will be placed</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" default="#[payload]" name="targetValue">
          <xs:annotation>
            <xs:documentation>An expression that will be evaluated against the operation's output and the outcome of that expression will be stored in the target variable</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="NackType" substitutionGroup="mule:abstract-operator" name="nack"></xs:element>
  <xs:complexType name="NackType">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractOperatorType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-reconnection-strategy"></xs:element>
        </xs:sequence>
        <xs:attribute type="mule:expressionString" use="required" name="ackToken"></xs:attribute>
        <xs:attribute type="xs:string" use="required" name="config-ref">
          <xs:annotation>
            <xs:documentation>The name of the configuration to be used to execute this component</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" xmlns:mule="http://www.mulesoft.org/schema/mule/core" type="PublishType" substitutionGroup="mule:abstract-operator" name="publish"></xs:element>
  <xs:complexType name="PublishType">
    <xs:complexContent>
      <xs:extension xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:abstractOperatorType">
        <xs:sequence minOccurs="0" maxOccurs="1">
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-byte-streaming-strategy"></xs:element>
          <xs:element minOccurs="0" maxOccurs="1" ref="mule:abstract-reconnection-strategy"></xs:element>
          <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="body"></xs:element>
          <xs:element type="xs:string" minOccurs="0" maxOccurs="1" name="properties"></xs:element>
        </xs:sequence>
        <xs:attribute type="mule:expressionString" use="required" name="destination"></xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputMimeType">
          <xs:annotation>
            <xs:documentation>The mime type of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="outputEncoding">
          <xs:annotation>
            <xs:documentation>The encoding of the payload that this operation outputs.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="xs:string" use="required" name="config-ref">
          <xs:annotation>
            <xs:documentation>The name of the configuration to be used to execute this component</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="messageId"></xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" name="messageGroupId"></xs:attribute>
        <xs:attribute type="mule:expressionInt" use="optional" name="deliveryDelay"></xs:attribute>
        <xs:attribute xmlns="http://www.mulesoft.org/schema/mule/anypoint-mq" type="com.mulesoft.extension.mq.api.config.DelayTimeUnitEnumType" use="optional" default="MILLISECONDS" name="deliveryDelayUnit"></xs:attribute>
        <xs:attribute type="mule:expressionBoolean" use="optional" default="true" name="sendContentType"></xs:attribute>
        <xs:attribute type="xs:string" use="optional" name="target">
          <xs:annotation>
            <xs:documentation>The name of a variable on which the operation's output will be placed</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="mule:expressionString" use="optional" default="#[payload]" name="targetValue">
          <xs:annotation>
            <xs:documentation>An expression that will be evaluated against the operation's output and the outcome of that expression will be stored in the target variable</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="java.util.concurrent.TimeUnitEnumType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="NANOSECONDS"></xs:enumeration>
          <xs:enumeration value="MICROSECONDS"></xs:enumeration>
          <xs:enumeration value="MILLISECONDS"></xs:enumeration>
          <xs:enumeration value="SECONDS"></xs:enumeration>
          <xs:enumeration value="MINUTES"></xs:enumeration>
          <xs:enumeration value="HOURS"></xs:enumeration>
          <xs:enumeration value="DAYS"></xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:propertyPlaceholderType"></xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  <xs:simpleType name="com.mulesoft.extension.mq.api.modes.SubscriberAckModeEnumType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="IMMEDIATE"></xs:enumeration>
          <xs:enumeration value="AUTO"></xs:enumeration>
          <xs:enumeration value="MANUAL"></xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:propertyPlaceholderType"></xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  <xs:simpleType name="com.mulesoft.extension.mq.api.modes.ConsumerAckModeEnumType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="IMMEDIATE"></xs:enumeration>
          <xs:enumeration value="MANUAL"></xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:propertyPlaceholderType"></xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  <xs:simpleType name="com.mulesoft.extension.mq.api.config.DelayTimeUnitEnumType">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="MILLISECONDS"></xs:enumeration>
          <xs:enumeration value="SECONDS"></xs:enumeration>
          <xs:enumeration value="MINUTES"></xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction xmlns:mule="http://www.mulesoft.org/schema/mule/core" base="mule:propertyPlaceholderType"></xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
</xs:schema>